# Generated by Django 4.1.6 on 2023-05-19 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4a9f2706-1050-4d5a-b09e-7722b127bd98')),
        ),
    ]
