# Generated by Django 4.1.6 on 2023-05-19 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_children_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2047e65c-9fbb-4ef9-bbd2-f63cc1b2b8e7')),
        ),
    ]
