# Generated by Django 4.1.5 on 2023-01-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='img',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
    ]
