# Generated by Django 4.1.2 on 2022-12-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_data',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='emp_data',
            name='check_out_date',
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='check_out_time',
            field=models.DateTimeField(),
        ),
    ]
